"""Add missing columns to linkedin_leads table

Revision ID: c5deb24611f9
Revises: 57bc92aad335
Create Date: 2025-11-07 11:34:59.002216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5deb24611f9'
down_revision = '57bc92aad335'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkedin_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('url_image', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('total_leads', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('job_title', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('entreprise', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('linkedin_leads', schema=None) as batch_op:
        batch_op.drop_column('description')
        batch_op.drop_column('pages')
        batch_op.drop_column('entreprise')
        batch_op.drop_column('job_title')
        batch_op.drop_column('total_leads')
        batch_op.drop_column('url_image')
        batch_op.drop_column('title')

    # ### end Alembic commands ###
